name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Build
      run: dotnet build FastEndpoints.Extensions.sln --configuration Release
      
    - name: Test
      run: dotnet test FastEndpoints.Extensions.sln --configuration Release --no-build --verbosity normal
  
  nuget:
    runs-on: windows-latest
    needs: [ build ]
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Create and push NuGet package
        run: |
          dotnet pack FastEndpoints.Extensions.sln -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/ductran95/index.json --skip-duplicate
